version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - D:/Docker/ElasticSearchMovies/elastic/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elasticsearchmovies

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    ports:
      - 5601:5601
    environment:
        ELASTICSEARCH_URL: http://elastic:9200
        ELASTICSEARCH_HOSTS: http://elastic:9200
    networks:
      - elasticsearchmovies

networks:
    elasticsearchmovies:
        driver: bridge